#!/bin/sh
set -e
cd "$(dirname "$(readlink -f "$0")")"
export LANG=
export WINEPREFIX="$PWD/wine"
[ -d "$WINEPREFIX" ] && [ -e "$WINEPREFIX/drive_c/divelog2srt" ]
cd "$WINEPREFIX/drive_c/divelog2srt"
exec wine dist/divelog2srt/divelog2srt "$@"
